apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xmjchvqz2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:1fb43718510664a51c03b1d02ef88f47d24560c4@sha256:f7bfc8049799a657f6455f3f9a3a33b335d79bf17e4f5958a3666f94ab0bbd00
          name: container-image
